### ISSUE TITLE
Check Use Statements As Well

### ISSUE THREAD

**Issue by sprankhub** [yireo/Yireo_ExtensionChecker#7] opened 2019-10-17 10:35 UTC
Currently, you collect dependencies only from the constructor. However, wouldn't it make sense to collect the dependencies from all `use` statements as well? For instance, if I implement the interface `Magento\Checkout\Model\ConfigProviderInterface`, I have a use statement `use Magento\Checkout\Model\ConfigProviderInterface;`. Hence, I would expect the extension checker to report a dependency on `Magento\Checkout`.

**Comment by jissereitsma** [comment] 2019-10-18 05:35
As I understand it, the PHP Reflection library that is used actually reads constructor arguments by parsing the PHP code like the PHP parser would. Imported namespaces (`use`) are supported. With PHPCS tokenization this would not be the case, but this is one of the reasons I choose Reflection instead.

**Comment by sprankhub** [comment] 2019-10-18 07:03
Do I read this correctly as "that is a good idea and should be implemented"? :)

**Comment by jissereitsma** [comment] 2019-10-18 07:31
No, you should read this as "already implemented". As I understand it. All my modules use imported namespaces and they worked fine so far with the ExtensionChecker....

**Comment by sprankhub** [comment] 2019-10-18 07:35
I do not think so. If you use the imported class in the constructor, it works. However, if you do *not* use the imported class in the constructor, but somewhere else, the dependency is not detected.

Use case: Define an observer and read e.g. the `Quote` from the event arguments. To be safe, you add a type check. Then you do have a dependency on `Magento_Quote`, which is currently not detected.

**Comment by jissereitsma** [comment] 2019-10-18 17:14
Ah, but there we go. That's what I misunderstood. Currently, `use` statements are not detected because they do not exist from the perspective of Reflection. However, as soon as the constructor method is parsed, imported namespaces are detected. One missing feature in the extension though is that other methods are not parsed for input arguments and/or return type hints, which causes the undetected dependencies that you were missing. So, by parsing other methods as well, this could be fixed. Added to the roadmap.

**Comment by HenKun** [comment] 2020-12-07 15:49
Additionally, as stated in the first comment, implemented interfaces would be great to be detected. They need not occur in constructor nor in method argument list or as return type. But it is a dependency anyway.

**Comment by jissereitsma** [comment] 2022-10-08 15:04
I believe that this is now picked up properly with the new architecture of component detectors. I'm going to close this issue, because I'm no longer able to reproduce the issue and believe it is fixed. Let me know if you encounter still an issue with this.

**Closed by jissereitsma** 2022-10-08 15:04 UTC
